# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDeveloper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#  pod 'RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'Moya/RxSwift'
  pod 'ObjectMapper'
  pod 'RxDataSources'
  pod 'Then'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'Reusable'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  
end
