platform :ios ,"8.0"
target "housebank" do
pod "JSONModel"
pod "AFNetworking"
pod "SDWebImage"
pod "Masonry"
pod "Reachability"
pod "MJRefresh"
pod "WebViewJavascriptBridge"
pod "pop"
pod 'BeeCloud/UnionPay'
pod 'ShareSDK3'
pod 'ShareSDK3/ShareSDKExtension'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'JKCountDownButton'
pod 'JSONKit'
pod 'MBProgressHUD'
pod 'Reachability', '>= 3.2'

end

