source 'https://github.com/CocoaPods/Specs.git'
platform :ios ,"8.0"
target "HeMeiHui" do
    pod 'AFNetworking'
    pod 'SDWebImage','= 5.0'
    pod 'Masonry'
    pod 'MJRefresh'
    pod 'WebViewJavascriptBridge'
    pod 'pop'
    pod 'BeeCloud/UnionPay'
    pod 'MOBFoundation'


pod 'mob_sharesdk', '= 4.2.6'
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'mob_sharesdk/ShareSDKUI'
#    # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
pod 'mob_sharesdk/ShareSDKExtension'
    
    pod 'JKCountDownButton'
    pod 'MBProgressHUD'
    pod 'Reachability', '>= 3.2'
    pod 'MJExtension', '~> 3.0.10'
    pod 'ReactiveObjC'
    pod 'YTKNetwork'
    pod 'CDDPagerController'
    pod 'SDCycleScrollView','>= 1.80'
    pod 'HHTransition'
    # 键盘管理
    pod 'IQKeyboardManager'
    pod  'FMDB'
    pod 'Bugly'
    pod 'VerifyCode', '= 3.0.1'
    pod 'JXCategoryView', '= 1.3.14'
    pod 'VTMagic'
    pod 'YYKit'
    pod 'AMapLocation'
    pod 'AMap2DMap'
    pod 'Realm'
    pod 'lottie-ios'
    pod 'AliyunPlayer_iOS/AliyunVodPlayerSDK'
    pod 'Texture'
    pod 'TZImagePickerController'
    pod 'ZFPlayer'
    pod 'ZFPlayer/AVPlayer'

end

